CMakeLists.txt
When OpenAL Soft is used as a subproject, installation of the headers and libraries is not always desired. This change makes it optional (enabled by default).
=> Make installation of headers and libraries optional

CMakeLists.txt
This is needed for multiarch layouts where the prefix is /usr/${host} but
where arch-independet files are installed to /usr/share.
=> Allow to override the share install dir

Alc/mixer_sse2.c, Alc/mixer_sse3.c, Alc/mixer_sse41.c
As previously discussed in IRC.  C, unlike C++, does not permit alignas() before the struct/union keyword, but it can be applied to the first member to equivalent effect.
=> Fix placement of alignas - fixes Mac OS X build

utils/alsoft-config/mainwindow.cpp
I considered putting INT_MAX or so here instead, but I think 4096 should be enough in practice, no?
=> alsoft-config: Raise source limit to 4096

appveyor.yml
Added Appveyor-CI (https://www.appveyor.com/) support for Windows builds validation (32/64 bit MSVS 2015).
As for Travis-CI it is required to register your project on https://www.appveyor.com/
=> build: added appveyor-ci script to verify windows build

CMakeLists.txt, utils/alsoft-config/CMakeLists.txt
CMake 2.8.5 added the GNUInstallDirs module, which provides various
variables following the CMAKE_INSTALL_*DIR pattern to allow users a more
flexible installation setup and to provide sensible defaults while
respecting distribution specific install locations like lib64 for RPM
based linux distributions or debian multiarch tuples.
=> Use GNUInstallDirs to place the build artifacts properly

CMakeLists.txt
Adds `-fno-gnu89-inline` to the GCC compiler flags.  My compiler has `-fgnu89-inline` enabled by default and OpenAL will not work with that setting.
=> Explicitly disable use of GNU89 inline semantics

.travis.yml, appveyor.yml
This PR is a work in progress
This PR (should) contain commits to allow that more parts of the project like backends or example programs are build and enforced to build to check for regressions in the build system.  Due to the nature of the CI services in question I can only test changes as external contributor by pushing to to this PR.  I will notify you when I consider the changes good enough for a review.
=> Enable and enforce dependencies on CI services.

Alc/helpers.c
I encountered this build error when trying to compile OpenAL Soft for Gentoo FreeBSD:
In file included from /usr/x86_64-gentoo-freebsd9.1/tmp/portage/media-libs/openal-1.18.1/work/openal-soft-1.18.1/Alc/helpers.c:44:0:
/usr/x86_64-gentoo-freebsd9.1/usr/include/sys/sysctl.h:799:25: error: unknown type name ‘u_int’
int sysctl(const int *, u_int, void *, size_t *, const void *, size_t);
^
Gentoo FreeBSD is barely maintained and 9.1 is an old version of freebsd-lib but according to the [sysctl manpage](https://www.freebsd.org/cgi/man.cgi?sysctl(3)) including both headers is the correct thing to do.
=> Fix build on Gentoo FreeBSD with freebsd-lib 9.1

README.md
This is not the most useful or important thing ever, but the README file had some markdown formating that were not applied by the website because of the lack of a .md extension.
I also wrapped the bit that explain how to call `cmake` on a code bock, and put the list of "thanks" at the end as an actual list.
This makes the landing page on GitHub display this file felling way better :wink:
=> Reformat README for a nicer display on github

Alc/helpers.c
Alc/helpers.c:738:30: error: use of undeclared identifier 'KERN_PROCARGS'
int mib[4] = { CTL_KERN, KERN_PROCARGS, getpid() };
/usr/include/sys/sysctl.h:
`#define	KERN_PROC_ARGS		7	/* get/set arguments/proctitle */`
there's no KERN_PROCARGS
=> freebsd fix: typo

examples/alffplay.cpp
I had compile errors with visual studio 2017 when building the alffplay binary:
```
3>alffplay.cpp
3>C:\projects\leviathan\ThirdParty\openal-soft\examples\alffplay.cpp(255): warning C4267: 'argument': conversion from 'size_t' to 'ALsizei', possible loss of data
3>C:\projects\leviathan\ThirdParty\openal-soft\examples\alffplay.cpp(715): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable conversion)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\ostream(488): note: could be 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_streambuf<char,std::char_traits<char>> *)'
...
```
I was able to fix this …
=> Added missing string include to alffplay

Alc/effects/modulator.c
This pull request fixes the carrier signal type from unipolar to bipolar because in a ring modulator the carrier signal is bipolar (DC=0). Originally, the implementation was correct, but it was changed in https://github.com/kcat/openal-soft/commit/a7ad6080f0d3fc783fd5e1811b961ab9efe79cde.
For example, references:
- [Refining Sound: A Practical Guide to Synthesis and Synthesizers](https://books.google.es/books?id=RlwWDAAAQBAJ&pg=PT213&dq=ring+modulator&hl=es&sa=X&redir_esc=y#v=onepage&q=ring%20modulator&f=false)
- [Introduction to Computer Music](https://books.google.es/books?id=mCpqmESEOEcC&pg=PA124&lpg=PA124&dq=ring+modulator+unipolar&source=bl&ots=uAjwND7dDh&sig=t5xKTVt5CQKMdAEnEDeVWADPmmQ&hl=es&sa=X&ved=0ahUKEwi6xI-8hbDbAhWFRhQKHcpCDfUQ6AEIPzAC#v=onepage&q=ring%20modulator%20unipolar&f= …
=> EFX: Modulator fixes

OpenAL32/Include/alMain.h
Shortly after I've opened the issue, I found the cause for the wrong return value of `IS_LITTLE_ENDIAN`: `__BYTE_ORDER__` is set to `__ORDER_LITTLE_ENDIAN__` instead of just `__LITTLE_ENDIAN__` (Android NDK r17 btw).
=> Correctly check byte order for newer Android compiler, fix #203

Alc/ALc.c
The common fallback order for libraries and applications which have an sndio and OSS backend is to first try sndio and only if that doesn't work try OSS.
I currently apply this patch to the FreeBSD port as the current behavior (OSS before sndio) represents a POLA violation vs the rest of the Ports Collection. This is likely a FreeBSD-only issue but it's similar to how it works with PulseAudio and ALSA on Linux.
=> Prefer sndio backend over OSS when both are enabled

common/threads.c, common/threads.h
After updating OpenAL Soft to 1.19.1 I noticed an excessive CPU usage in GZDoom running on macOS. One core is fully occupied by OpenAL event thread.  
Bisecting changes revealed that the issue was introduced in cb8545346d227ba85a4a98c3897b5cdb1ea86d26.
The problem is POSIX unnamed semaphore doesn't work on macOS. [Here](https://stackoverflow.com/questions/27736618/why-are-sem-init-sem-getvalue-sem-destroy-deprecated-on-mac-os-x-and-w) is a related Stack Overflow discussion. Using Grand Central Dispatch semaphore instead of `sem_...` functions solved the issue for me.
=> Use GCD semaphore on macOS

CMakeLists.txt
Regression was introduced in 5ec11a017c.
On MSVC there was this macro in config.h:
```
#define ASSUME_ALIGNED(x, y) x
```
While it was `ASSUME_ALIGNED(filter + offset, 16)` it was expanded to `filter + offset`, adding `offset * sizeof(*filter)` bytes to the `filter` pointer value.
But after it became `(const __m128*)ASSUME_ALIGNED(filter + offset, 16)` it was expanded to `(const __m128*)filter + offset`, adding `offset * sizeof(__m128)` bytes to the `filter` pointer value and completely killing captured data on Windows :(
PS macros are evil :)
=> Fix Resample_bsinc_SSE pointer casts.

Alc/alc.cpp, Alc/alcontext.h, OpenAL32/Include/alAuxEffectSlot.h, OpenAL32/Include/alListener.h, OpenAL32/Include/alSource.h, OpenAL32/alSource.cpp
Msvc142 in VS2019 preview 2 doesn't allow std::atomic_flag to be initialized by a bool. Call test_and_set in the constructors instead.
=> Fix compiling problems on VS2019 with vc142 toolset

common/almalloc.h
Strangely, building ``common/almalloc.cpp`` from ``master`` under LLVM 8.0.0 gives me an ambiguous call to ``destroy_at`` in the header. The compiler can't decide between the function from ``<memory>`` and the one from ``al`` namespace. I presume the intention was to call the latter, so I've just preffixed the call with ``al::`` to resolve the error.
For reference, here is the error log:
```
FAILED: src/3rdparty/openal-soft/CMakeFiles/OpenAL.dir/Alc/mastering.cpp.o
/usr/bin/clang++  -DAL_ALEXT_PROTOTYPES -DAL_BUILD_LIBRARY -DAL_LIBTYPE_STATIC -DLIBM_COMPILING_FLT32 -DLUA_USE_LINUX -DPLATFORM_UNIX=1 -DSTREFLOP_SSE -D_LARGEFILE_SOURCE -D_LARGE_FILES -D_POSIX_C_SOURCE=200112L -D_SILENCE_CXX17_CODECVT_HEA
DER_DEPRECATION_WARNING -D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING …
```
=> Fix ambiguous calls to destroy_at

Alc/alc.cpp
reinterpret_cast and C-style casting is no longer a constexpr in GCC9. Need to fall back to const instead.
=> Fix the error "a reinterpret_cast is not a constant expression" in GCC 9

Alc/mixer/mixer_c.cpp
This change fixes compilation problems on gcc 9.1 with -std=c++17.
=> Add noexcept to match the signature of sampler functions

utils/makemhr/loaddef.cpp, utils/sofa-info.cpp
Fixed some errors. This will allow you to build, but makemhr will fail if you do not add a directory containing getopt.h as an additional include.
=> Fixed makemhr and sofa-info errors

alc/effects/pshifter.cpp, common/alnumeric.h
Move inline `double2int` function to `alnumeric.h` from `pshifter.cpp`.
=> Move double2int function

al/auxeffectslot.cpp
It resolves wrong logic when creating more than 1 aux slot at time in a batch
=> pass proper effects slot number to AddActiveEffectSlots

common/alcomplex.cpp
the caller in fshifter is already doing the same job by putting 0 for the imaginary part
=> removed unnecessary loop

alc/effects/modulator.cpp
MSVC 2015 and above returns the expression according to its datatype.
In this case, `((index>>(WAVEFORM_FRACBITS-2))&2)` returns 4294967295 instead of -1, with the result that one can imagine.
One example,  in the issue #351, PenguinDOOM made binaries for testing with MSVC 2017. These binaries are affected.
Please, review and merge it, thanks.
=> EFX: Modulator fix

native-tools/CMakeLists.txt
"By default C and CXX are enabled if no language options are given."
https://cmake.org/cmake/help/v3.17/command/project.html
I have ran into problems when cross-compiling inside of a Docker container where there's only a C compiler installed.
=> Don't require a C++ compiler for native-tools

cmake/FindDSound.cmake, cmake/FindMySOFA.cmake, cmake/FindOpenSL.cmake
Using CMake 3.17.0 with the Visual Studio 2019 generator, I get warnings during configuration about names passed to `find_package_handle_standard_args()`. While I am able to generate a sln file, it fails to open properly.
Two warnings are caused by case issues, and a third is caused by including the `FindWindowsSDK.cmake` file instead of calling `FIND_PACKAGE()`.
My changes fix these warnings and allow me to generate a sln file for openal-soft that opens successfully.
=> Fix find_package_handle_standard_args name mismatch warnings

CMakeLists.txt
When using openal-soft as a git submodule, the "build_version" target currently gets generated. This causes any cmake targets that link against openal-soft to request a build every time they are launched in Visual Studio. I've added a new cmake option to allow disabling the creation of the "build_version" target to get around this issue.
=> Add option to disable "build_version" cmake target

utils/makemhr/loaddef.cpp, utils/openal-info.c
OpenAL-Soft failed to compile on some GCC version:
https://travis-ci.com/github/ArthurSonzogni/smk/jobs/318304162
It has regressed likely after:
https://github.com/kcat/openal-soft/commit/c83609277bed4be4ef40ed306bf2c57fefa19519
va_start is defined in:
- stdarg.h
- cstdarg
The repository is using it from:
- al/error.cpp
- al/filter.cpp
- alc/alu.cpp
- alc/helpers.cpp
- common/alexcpt.cpp
- utils/makemhr/loaddef.cpp
- utils/openal-info.c
This patch is adding its definition in the files missing it:
- utils/makemhr/loaddef.cpp
- utils/openal-info.c
Bug: https://github.com/kcat/openal-soft/issues/413
=> Add missing <cstdarg>

alc/hrtf.cpp, alc/panning.cpp
When compiling with MSVC 2019 I'm getting the following warning at these 3 locations:
`warning C4834: discarding return value of function with 'nodiscard' attribute`
=> Silence warning about unused return values

alc/backends/opensl.cpp, examples/altonegen.c
Add a gain command-line argument to altonegen.c.
Fix a spelling error in an error message in opensl.cpp
Fix compilation of some of the examples by guarding the include of win_main_utf8.h
=> Add a gain argument to altonegen

alc/backends/pulseaudio.cpp
libpulse can read application name from an [environment variable](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/ApplicationProperties/) and [fallbacks to binary name by default](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/pulsecore/proplist-util.c#L203-208). However, openal forces binary name as application name and makes impossible to set it from application :(
=> Don't force application name with pulseaudio

alc/backends/coreaudio.cpp
AudioBufferList contains a variable length array of mNumberBuffers elements, so it should not be created with the default constructor like usual class instances.
Unfortunately, Apple developer site documentation is literally empty for this API. There is a bunch of comments in framework's header files.
Here is the correct usage of AudioBufferList pointer from Chromium: https://chromium.googlesource.com/chromium/src/media/+/008a1abc573e1f8bcf513b50ce48a923b30ef130/audio/mac/audio_manager_mac.cc#266
There were occasional crashes because of memory corruption which was confirmed by address sanitizer
=> Fix getting of device channel count in CoreAudio backend

CMakeLists.txt
* Android doesn't have dbus, logspam is annoying
=> CMakeLists: add QUIET to Dbus1 find_package()

alc/backends/sndio.cpp
Hello! I found a crashes of applications while capturing audio using openal with the sndio backend. I also discovered a fix for this.
Problem description:
OpenBSD 7.0 (current), sndio.
openal 1.21.1 + 620836f173ae6fc4505d0634984e0f2c46166367 and 1fd4c865fc084f134363db5155361d5483679235 (the most recent commit in alc/backends/sndio.cpp for now).
```
> ./alrecord -device "SndIO Default" -o ./test.wav
Opened "SndIO Default"
Recording './test.wav', Signed 16-bit, Mono, 44100hz (4 seconds)
Captured 0 samples[ALSOFT] (EE) Cannot set priority level for thread
zsh: segmentation fault (core dumped)  ./alrecord -device "SndIO Default" -o ./test.wav
(gdb) bt
#0  _aucat_pollfd (hdl=0xc58eb866ea0, pfd=0x0, events=1) at /usr/src/lib/libsndio/aucat.c:561
#1  0x00000c59601f665b in (anonymous …
```
=> Fix crashes in SndioCapture::recordProc

alc/alu.cpp
It seems like a recent change to cone angle calculation broke the cone feature, as I found out after an updated build of openal-soft broke cones in a project I was working on. 
A quick debugging session showed angles to be negative numbers, which caused a gain of 1.0f to be used regardless of the actual angle. This fix addresses that, instead inverting the dot product of the two normals to achieve the desired angle and correct gain.
=> Fix cone angle calculation

core/fpu_ctrl.h
Found using -Wextra-semi warning.
=> Remove extra ';' after member function definition

al/event.cpp
MSVC produced the warning `openal-soft\al\event.cpp(204,36): warning C4834: discarding return value of function with 'nodiscard' attribute` due to the unnamed std::lock_guard
=> Fixed compiler warning on MSVC

common/albit.h
static variables are not permitted in `constexpr` functions. Unlike with functions, `constexpr` is not a suggestion with variables, and need to evaluate to a constant expression. So making them static when they are generated at compile time will have no additional performance benefit within a local scope.
It is also better to have non static `constexpr` variables in a `constexpr` function than `constexpr` variables in a non `constexpr` function because it allows the functions to be completely optimized away, including the existence of the variable.
Yes with optimization turned off the `constexpr` function has 1 more line of unnecessary ASM, but with any optimization at all the `constexpr` functions dissapears. (The generated example generates the same ASM with -O1 and -O2, and similar …
=> constexpr functions are not allowed to have static variables, and if they are constexpr anyways then them being static has no benifit

.github/workflows/ci.yml
Provides an alternative Windows binary download location that expires in 3 months (2 months longer than Appveyor)
=> Upload Win32 and x64 artifacts to Github actions

common/opthelpers.h
Fix compilation error in Clang using C++20.
Tested on Clang 13.0.0
=> Added missing header file for std::assume_aligned. (C++20)

al/auxeffectslot.cpp, al/auxeffectslot.h, al/eax/call.cpp, al/source.cpp, al/source.h, alc/context.cpp, alc/context.h
Summary
- [EAX_FX_SLOT] Fix EAXGet for EAX5
- [EAX_FX_SLOT] Mark sources as changed instead of commiting them to catch up with changes in FX slot
- [EAX_CALL] Clear defer flag for immediate-only properties  
EAX allow to set "defer" flag on immediate-only properties. If we don't clear our flag then "applyAllUpdates" in EAX context won't be called.
- [EAX_FX_SLOT] Fix slot's occlusion contribution
- [EAX_SOURCE] Fix getting active FX slot IDs
- [EAX_CONTEXT] Fix committing of a property value
- [EAX_SOURCE] Fix Room and RoomHF contribution  
Those properties should be taken into account only for environmental effect slot (see pp. 60-61 of "EAX® 4.0 Programmer’s Guide").
- [EAX_SOURCE] Skip occlusion calculation if occlusion property is zero
- [EAX_FX_SLOT] Fix defaults for current …
=> [EAX] Various fixes

al/eax/api.h
Guiddef.h uses a separate header guard to define the GUID operators, in the current codebase this won't cause any issue, but i got such error while fiddling a bit with the program and including something that ended up including all the various windows headers, that ended up including Guiddef.h, causing the error as by not finding the macro declared, it ended up declaring the inline operators as well.
=> Fix possible C2084 compiler error

alc/backends/pipewire.cpp
Adds the additional pipewire node class `media.class = Audio/Source/Virtual` to the list of valid classes usable by the library.
My specific use case: I run my hardware microphone into a Carla software effects rack and use a virtual source node as a post-processed microphone for applications. Excluding nodes with the `Audio/Source/Virtual` media class makes it so OpenAL Soft applications cannot access this virtual device and default back to the hardware node.
Pipewire documentation: https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#single-nodes
=> Add media class for Audio/Source/Virtual as a valid node

core/rtkit.cpp
=> rtkit: remove syscall include

.github/workflows/ci.yml
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/upload-artifact
This should fix 2 of the 3 warnings here: https://github.com/kcat/openal-soft/actions/runs/3303596206 
like this https://github.com/ThreeDeeJay/openal-soft/actions/runs/3307517024
by updating to this https://github.com/actions/upload-artifact/releases/tag/v3.1.1 
The other warning is more of a heads up of the macOS runner being updated so it should go away eventually
=> Update upload-artifact to remove warning

router/router.cpp
According to the programming guide and the specification, those functions may be used by extensions. However, Creative's hardware OpenAL chose to not implement stub functions for those that they do not use. Currently they use only alBufferi for X-RAM related functions.
Other implementations, such as OpenAL Soft and wrap_oal implement stub functions for those methods therefore they work.
This commit turns those functions optional, just like they were in the old FOSS router. Consumers of the router will receive a nullptr as expected for not implemented methods if they load them using alGetProcAddress, which I believe is the correct way to do so. That is, the context must be current before loading al* functions.
=> Fix router not loading on Creative's hardware OpenAL

.github/workflows/makemhr.yml
This workflow [builds makemhr.exe including dependencies (libmysofa, zlib, etc)](https://github.com/ThreeDeeJay/openal-soft/actions/runs/3457267682/jobs/5770580210) whenever anything under utils/makemhr or the workflow is updated.
It also uploads artifacts and [(pre)releases it with its own tag](https://github.com/ThreeDeeJay/openal-soft/releases/tag/makemhr) for a [permanent, up-to-date download link](https://github.com/ThreeDeeJay/openal-soft/releases/download/makemhr/makemhr.zip).
=> Add GitHub actions workflow to build utils/makemhr on update

alc/backends/opensl.cpp
This crash happens when you use alcDevicePauseSoft in android and then use alcDeviceResumeSoft
Seems like there should be "->" instead of "."
=> Fix RingBuffer crash in OpenSL backend

alc/backends/oboe.cpp
This change should handle handphone call event properly and fix crash at stop (because the mStream was disconnected by system when handphone call income)
=> Improve oboe backend

common/threads.cpp, common/threads.h
This PR addresses the build on macOS < 10.7 and PowerPC, which are currently broken for two reasons:
1. Unconditionally using `libdispatch`.
2. Missing define of `__STDC_FORMAT_MACROS`.
With these fixed, `openal-soft` builds successfully.
=> Fixes for Darwin: fallback for systems without libdispatch; fix for undefined types from inttypes.h

.github/workflows/ci.yml
@kcat  The latest code has compile error for ios build,
```txt
/Users/runner/work/openal-soft/openal-soft/alc/backends/coreaudio.cpp:44:10: fatal error: 'IOKit/audio/IOAudioTypes.h' file not found
```
refer to: https://github.com/halx99/openal-soft/actions/runs/5133473000/jobs/9236097000#step:5:385
=> Add ios ci check

.github/workflows/ci.yml, .github/workflows/makemhr.yml
The following updates are performed:
* update [`actions/checkout`](https://github.com/actions/checkout) to v3
* update [`actions/upload-artifact`](https://github.com/actions/upload-artifact/) to v3.1.2
=> Update GitHub Actions CI

alc/backends/coreaudio.cpp
The library currently fails to compile under macos with clang with `-Werror=return-type`. This patch fixes the issue.
=> Return noErr from DeviceListenerProc

alc/alconfig.cpp, common/strutils.cpp, core/helpers.cpp
This disables functionality that is not available on the xbox similar to `ALSOFT_UWP`.
=> disable unavailable functionality on xbox

OpenALConfig.cmake.in
Fixes the following warning with CMake 3.27:
```
CMake Deprecation Warning at /lib/cmake/OpenAL/OpenALConfig.cmake:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
CMakeLists.txt:75 (find_package)
``
=> Fix CMake deprecation warning in OpenAL config

CMakeLists.txt, common/almalloc.h, common/alspan.h
compiler errors without this patch, refer to: https://github.com/kcat/openal-soft/actions/runs/6275514636/job/17043155913
=> Compile with c++20 support

alc/alc.cpp, alc/backends/base.h, alc/backends/coreaudio.cpp, alc/backends/coreaudio.h, alc/backends/pipewire.cpp, alc/backends/pipewire.h, alc/backends/pulseaudio.cpp, alc/backends/pulseaudio.h, alc/backends/wasapi.cpp, alc/backends/wasapi.h, alc/events.cpp, alc/events.h, alc/export_list.h, include/AL/alext.h, utils/openal-info.c
The purpose of this PR are allow to retrieve which events are supported and if events are fully supported or if some case isn't managed for some reason.
Here, since extension isn't release, I would like to propose this addition to allow consumer of this extension to known eventual limitation on runtime (Because backend don't implement some event for example)
For exemple only some backends provide system events:
* pipewire -> Full support of extension
* wasapi -> Full support of extension
* pulseaudio -> Support of add and remove devices events only
* coreaudio -> Support of default device change only
Here, for complete this goal, i propose following addition :
* alcEventIsSupportedSOFT in ALC_SOFT_system_events extension
=> Add query fonction in ALC_SOFT_system_events unreleased extension

utils/openal-info.c
Small PR to add sources values inside openal-info
=> feat(openal-info): Add values related to sources inside openal-info.c

al/effects/effects.h, al/filter.cpp, alc/backends/base.h, alc/context.h, core/ambdec.cpp, core/device.h, core/logging.h
With gcc, mingw uses gnu_printf. With clang, printf is used as it does not support gnu_printf. Use the internal header to match this properly.
Probably should add CI.
=> fix printf format for MinGW

alc/backends/portaudio.cpp
Currently, playback using portaudio backend does not work at all due to simple but critical mistake. This PR is to fix that.
=> Fix a bug that playback via portaudio does not work at all

common/almalloc.h
To silence the `/__w/Q2RTX/Q2RTX/extern/openal-soft/common/almalloc.h:15:2: warning: extra ';' [-Wpedantic] };` warning
=> Remove extra ';' from common/almalloc.h

CMakeLists.txt
Fixed linking when building as a CMake subdirectory with MinGW. The problem is described in issue #990
=> Fixed compilation as a subdirectory with MinGW

common/almalloc.h
Prevents 
```
common/alspan.h:105:57: error: call to 'to_address' is ambiguous
constexpr explicit span(U iter, index_type) : mData{to_address(iter)} { }
```
when `std::to_address` can be found via ADL.
=> Use std::to_address if available

.github/workflows/ci.yml
Context: https://github.com/kcat/openal-soft/issues/1010 and https://github.com/kcat/openal-soft/issues/824
This builds [32-bit/armeabi-v7a](https://github.com/ThreeDeeJay/openal-soft/actions/runs/10224078457/artifacts/1771370955)  and [64-bit/arm64-v8a](https://github.com/ThreeDeeJay/openal-soft/actions/runs/10224078457/artifacts/1771371327) libopenal.so for Android that can replace older/generic OpenAL library from Android apps/games (if using root to access `/data/app/*hash*/*package*/lib/...`), or just include it in an android app/game rebuilt from source. Tested in [sView](https://youtu.be/ssmLgkbRMh0) (32-bit) and IdTech4A/Quake4 (64-bit).
Though apparently an update in android or something on my end broke apps' ability to load `/etc/openal/alsoftrc.config` (the only location that …
=> Build for Android (32 and 64-bit) and upload as workflow artifacts

.github/workflows/ci.yml
Fixes a minor typo from https://github.com/kcat/openal-soft/pull/1008
=> Remove "v" from commit hash in release title

.github/workflows/utils.yml
- Includes makemhr, sofa-info, alrecord, altonegen, openal-info and allafplay Windows executables in [utils.zip](https://github.com/ThreeDeeJay/openal-soft/releases/download/utils/utils.zip)
- Uses my libmysofa fork that fixed the `Invalid format` error by removing a [filesize/density limit](https://github.com/hoene/libmysofa/issues/195#issuecomment-1370881871), so that makemhr is able to convert larger SOFA files (like [EAC](https://github.com/davircarvalho/Individualized_HRTF_Synthesis) HRTFs with 5° elevations/azimuths)
[v1.3.2](https://github.com/hoene/libmysofa/releases/tag/v1.3.2) (latest upstream)
[My fork](https://github.com/hoene/libmysofa/compare/main...ThreeDeeJay:libmysofa:main) (just a two-liner so let me know if you'd rather fork and remove limit yourself or if I should …
=> Upgrade makemhr workflow to build and upload utils

.github/workflows/utils.yml
I decided to submit [your suggestion to set a higher but safe SOFA limit](https://github.com/kcat/openal-soft/pull/1026#issuecomment-2268680856) as a [PR in the official libmysofa repo](https://github.com/hoene/libmysofa/pull/221) and thankfully it was accepted and merged. So I figured it's time to switch off my temporary fork and use the latest official commit directly.
To verify it, you can try the [test with old makemhr](https://www.dropbox.com/s/ow1f3t46tw4tuvr/makemhr-f176484%2BEAC.SOFA-05ac8cc_InvalidFormat.7z?dl=1) which should fail with `Invalid error`
And updating makemhr.exe to [the new one](https://github.com/ThreeDeeJay/openal-soft/releases/download/utils/utils.zip) should allow converting it:
```
Generating "EAC_Default_CustomGrid_-90_90_5_0_360_5_48kHz_UniqueCartesianCoordina …
```
=> Switch to the official libmysofa repo

.github/workflows/utils.yml
Apparently the previous fix caused some [build errors](https://github.com/hoene/libmysofa/issues/224) which were fixed [here](https://github.com/hoene/libmysofa/pull/226), which is included in the [latest stable release](https://github.com/hoene/libmysofa/releases/tag/latest).
=> Update libmysofa to stable release (v1.3.3)

alc/backends/coreaudio.cpp
Hi! I work on the a game engine that makes use of OpenAL Soft. We noticed, on macOS, that OpenAL was not properly providing surround sound to some hardware devices like the Apple Studio Display. The Studio Display is a 5.1.2 device, but OpenAL was treating it as a stereo device.
After some research - I found the CoreAudio backend for OpenAL Soft is not properly querying the channel count of devices. If the device type was overridden in the OpenAL config - surround output would work. But OpenAL would not auto detect surround devices on macOS.
This change implements a correct query of the device channel count by querying the preferred channel setup of the underlying device/audio unit. I took some notes from how PulseAudio handles this - and I also populate FmtChans by comparing against a …
=> Adding channel detection to CoreAudio backend

include/AL/al.h, include/AL/alc.h
This resolves issues consuming openal-soft in projects that don't explicitly specify a C++ standard of C++11 or newer.
This also handles the fact that `__cplusplus` is not set properly in MSVC (always claiming to be 199711L) which prevented both the C++11 noexcept and the C++17 noexcept annotations from taking effect.
(See https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/ for details, including the mandatory command-line option to opt-in to standard `__cplusplus` behaviour)
=> Only use noexcept in public headers on >= C++11

CMakeLists.txt
vcpkg provides a packaged version of CppWinRT with its own CMake target, so if that's available then we can use it directly rather than trying to install it from NuGet.
This resolves issues building for UWP within vcpkg, because vcpkg uses Ninja internally and that doesn't pick up the props definition from the NuGet package.
=> Support finding CppWinRT through vcpkg

core/converter.cpp
GCC can't elide the copy because of two returns.
=> fix GCC Wnrvo warning

README.md
Just a small update to the bindings list to include LWJGL as another Java wrapper and Multiplatform OpenAL for Kotlin/Native from myself.
=> Update bindings list to include LWJGL and Multiplatform OpenAL

CMakeLists.txt, alc/alconfig.cpp, common/filesystem.cpp, common/filesystem.h, common/ghc_filesystem.h, core/ambdec.cpp, core/helpers.cpp, core/hrtf.cpp, examples/allafplay.cpp, utils/makemhr/loaddef.cpp, utils/makemhr/makemhr.cpp
This brings in https://github.com/gulrak/filesystem as a "polyfill" for the C++17 filesystem API, particularly on older macOS versions where it's not part of the system C++ library. This should resolve #1065.
If possible, it will use the std::filesystem API, but when targeting macOS versions without support it will use the GHC implementation instead.
This uses the latest master branch of gulrak/filesystem because the current tagged release doesn't work properly on macOS.
I opted to just drop this in the common folder for ease of use, since it's a single file and that's what was done with pffft, but I could try to put it in a top-level vendor folder similar to fmt if that's the preferred approach.
=> Use GHC::filesystem for std::filesystem compatibility

configs/HRTF+WASAPI Exclusive/alsoft.ini, configs/WASAPI Exclusive/alsoft.ini
Minimal drop-in configuration to enable WASAPI exclusive at the lowest available buffer/period size as well as another config with HRTF also enabled since it can benefit from lower latency for slightly higher binaural accuracy like during fast sound or camera movements.
I was considering making GitHub actions generate separate pre-configured builds with it but that seems like overkill, unless there's more demand for low latency in the future 🤔
=> WASAPI exclusive config

.github/workflows/ci.yml
Just noticed [this license file](https://github.com/kcat/openal-soft/blob/master/LICENSE-pffft) was missing from the GitHub Actions CI build so I figured I'd add it to comply with [this](https://github.com/kcat/openal-soft/blob/05298364fb9bd3072e52839d9ced6a8ba7b0a03d/LICENSE-pffft#L25-L28) 😬
Will probably need to do the same for the DSOAL workflow 🤔
=> Include PFFFT license in CI build
