Alc/ALu.c
Fix a link error created by ab6622a8d6912fa6ff8da9caa3fcaf96047ca14a
=> Fix resample_fir4 link error

Alc/backends/coreaudio.c
This prevents a deprecation notice from being output to stdout when alcOpenDevice is called in Mac OS X 10.11. (bug #20)
The new API calls require Mac OS X 10.6 or newer at runtime.
I could update it to use the old calls when the OS X deployment target (or maybe runtime OS) is <= 10.5, if you want, but there is so little usage of that OS these days and it would make the code a bit harder to maintain, so it's not really worth it in my opinion.
=> CoreAudio: replace deprecated Carbon API calls with AudioComponent APIs

Alc/backends/oss.c
Added device enumeration for OSSv4 using SNDCTL_SYSINFO and SNDCTL_AUDIOINFO.
=> Added device enumeration support for OSSv4

examples/alffplay.c
fix audio play error in sample
=> fix audio play error in sample alffplay

examples/alffplay.c
Closes https://github.com/kcat/openal-soft/issues/48.
=> Fix for ffmpeg.

CMakeLists.txt, cmake/FindDSound.cmake, cmake/FindWindowsSDK.cmake
I know dsound may not be used as the first backend, and don't know if it's any use for you.
But I updated cmake file to find dsound on windows
Thanks
=> Added cmake support for dsound and windows 8/10 SDKs

.travis.yml, Alc/hrtf.c, Alc/hrtf_res.h, Alc/hrtf_res.rc, CMakeLists.txt, appveyor.yml, utils/native-tools/CMakeLists.txt, utils/native-tools/bin2h.c
Discussion is in #111 
Embedding now works with static OpenAL library too
=> Cross-platform embedding of HRTF data

Alc/helpers.c
GetProcPath doesn't work on FreeBSD since it relies on the Linux proc filesystem.  So I added a FreeBSD implementation that uses `sysctl`.
=> Implement GetProcPath for FreeBSD

COPYING
Remove bad chars, remove section that shouldn't be there.
=> Fix COPYING

cmake/FindWindowsSDK.cmake
Build successfully with Win10 SDK 10.0.17763.0 on my machine.
=> Support build with latest Win10 SDK

Alc/effects/vmorpher.cpp
Added few comments, unify some code style to be consistent with the others oal soft effects.
Fixed a logic error during filter params copy.
The part which includes pitch shifter is ready and I'll soon send the PR but I don't like the fact that I do a lot of boilerplate because of code duplication. If for you is fine I can unify the code between pshifter.cpp and vmorpher.cpp to avoid code duplication. My idea is to add a utility function in al_complex.h and a structure which represent all the buffers for the FFT pitch shifting. That will allow much easily to perform pitch shifting around the codebase, in just few lines of code.
=> misc fixes and improvements for Vocal Morpher

Alc/effects/vmorpher.cpp
=> pitch shift for formant filters

alsoftrc.sample, utils/alsoft-config/mainwindow.cpp, utils/alsoft-config/mainwindow.ui
In alsoft-config app, add an option on _Effects_ tab (subsection _Enable Effects_).
=> Alsoft-config: Add vocal morpher effect

alc/effects/fshifter.cpp
This pull request implements the frequency shifter processing for L and R channels.
Review and merge it, please
Thanks
=> EFX: Update Frequency shifter

alc/alc.cpp
The last return statement could not be reached.
=> Fix unreachable code warning

alc/backends/sndio.cpp
So far the sndio backend only supports Mono and Stereo, but sndio
supports up to 16 channels (64 in their current git code).
This adds support for all the openal-soft formats (DevFmt*).
I tested this on Linux with 5.1 surround speakers.
As a sidenode, it might make sense to mention sndio *somewhere* in the docs or alsoftrc.sample to people know it's supported and know how the driver is called for `drivers = ...` and `ALSOFT_DRIVERS` (for the other backends it can be looked up in their alsoftrc config section, but sndio doesn't have one as it doesn't seem to have configurable options).
=> sndio: Support more than 2 channels

alc/backends/pulseaudio.cpp
Pass nullptr to pulse when enumerating devices and in other in order to avoid device open, fix #457 and allow pulse to move stream to new default device when it changes (look https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/14.0/#significantroutingchangestodefaultsinkssources)
=> Pass nullptr to pulse for default device

CMakeLists.txt
This patch will fix to avoid cause check_include_file return unexpected result
- build tools: Gradle -> cmake -> Ninja
- build target: android x86
- Reproduce step action: https://github.com/halx99/openal-soft/actions/runs/834150596
- Fixed action: https://github.com/halx99/openal-soft/actions/runs/834168309
=> Fix check_include_file return unexpected result

CMakeLists.txt, config.h.in, core/helpers.cpp
That allows the logic to work on non-FHS distros like NixOS
=> Search the installation data directory

al/auxeffectslot.cpp, al/auxeffectslot.h, al/eax/call.cpp, al/eax/call.h, al/eax/effect.h, al/eax/fx_slots.cpp, al/eax/fx_slots.h, al/eax/utils.h, al/effects/autowah.cpp, al/effects/chorus.cpp, al/effects/compressor.cpp, al/effects/distortion.cpp, al/effects/echo.cpp, al/effects/effects.cpp, al/effects/effects.h, al/effects/equalizer.cpp, al/effects/fshifter.cpp, al/effects/modulator.cpp, al/effects/pshifter.cpp, al/effects/reverb.cpp, al/effects/vmorpher.cpp, alc/context.cpp, alc/context.h
Also removes the EAX deferring of FX slot properties.
=> [EAX] Use separate FX slot state for each version

CMakeLists.txt
=> tvos support

al/effects/reverb.cpp, common/win_main_utf8.h
hi @kcat,
I think you'll like these little changes in PR.
=> Fixed bug, possible overflow type and non-void no return

.github/workflows/ci.yml, .gitignore, CMakeLists.txt, tests/CMakeLists.txt, tests/example.t.cpp
Hi, this is a PR for adding gtest integration, in reply to 
https://github.com/kcat/openal-soft/issues/857
https://github.com/hsdk123/openal-soft/actions/runs/5237440993/jobs/9455621772
=> Add gtest integration

CMakeLists.txt, al/buffer.cpp, al/eax/api.h, al/source.cpp, alc/alu.cpp, alc/backends/pipewire.cpp, alc/backends/sndio.cpp, alc/backends/winmm.cpp, alc/effects/reverb.cpp, core/filters/nfc.h, core/helpers.cpp, docs/ambisonics.txt, examples/alconvolve.c, examples/alhrtf.c, examples/allatency.c, examples/alloopback.c, examples/almultireverb.c, examples/alplay.c, examples/alreverb.c, examples/altonegen.c
This pull request fixes some typos, no functional changes intended.
=> Fix some typos

al/effects/chorus.cpp
I have no experience with this code base so someone should probably review this before merging.
=> Fix if-comparison

CMakeLists.txt, alc/alconfig.cpp, alc/backends/wasapi.cpp
This will make openaal-soft codebase not limited in c++17, could build on c++20
=> UWP: migrate C++/CX to C++/WinRT

alc/backends/wasapi.cpp
refer: https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx#port-platformexception-to-winrthresult_error
=> Fix cppwinrt exception type capture

.github/workflows/utils.yml
I noticed [allafplay.cpp was recently updated](https://github.com/kcat/openal-soft/commits/master/examples/allafplay.cpp) but [utils.zip](https://github.com/kcat/openal-soft/releases/download/utils/utils.zip) hasn't been updated since Aug 8, because utils.yml wasn't watching changes in the examples/ folder so I decided to fix that.
=> Trigger utils workflow upon changes in examples/

examples/altonegen.c
I'm hoping that using this with the wave backend will help diagnose #1128
=> Add altonegen --position arg
